# -*- coding: utf-8 -*-
"""hurriyet_gazete.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ZaJhqXId8SJ2sM_2OrlWfmRWkai-2we
"""

!pip install requests

!pip install beautifulSoup

import pandas as pd
import requests
from bs4 import BeautifulSoup

url2 = "https://www.hurriyet.com.tr/"

response2 = requests.get(url2)

soup2 = BeautifulSoup(response2.content, "html.parser")

title = soup2.find_all("span", attrs={'class':'box__title box-sm__title' })

title

title3 = soup2.find_all("span", attrs={'class':'box__title box-xl__title' })

title3

title4 = soup2.find_all("a", attrs={'class':'current-news__title' })

title4

html_list = ['''
    <a class="current-news__title" href="/gundem/ogretmenler-odasinda-skandal-fotograf-okul-mudurunun-pes-dedirten-yasak-aski-once-ogretmenle-sonra-veliyle-iliski-yasadi-42374852" target="_blank" title="Öğretmenler odasında skandal fotoğraf! Okul müdürünün pes dedirten yasak aşkı">Öğretmenler odasında skandal fotoğraf! Okul müdürünün 'pes' dedirten yasak aşkı</a>,
    <a class="current-news__title" href="/gundem/gamzenin-kahreden-olumu-kavsak-ve-yaya-gecidi-projesi-iptal-edilen-bolgede-hayatini-kaybetti-42374821" target="_blank" title="Gamzenin kahreden ölümü: Ağaçta çantası bulundu">Gamze'nin kahreden ölümü: Ağaçta çantası bulundu</a>,
    <a class="current-news__title" href="/gundem/13-yasindaki-kiz-cocugunu-sosyal-medyadaki-yorum-yuzunden-bicaklamis-42374862" target="_blank" title="13 yaşındaki kız çocuğunu sosyal medyadaki yorum yüzünden bıçaklamış">13 yaşındaki kız çocuğunu sosyal medyadaki yorum yüzünden bıçaklamış</a>,
    <a class="current-news__title" href="/sporarena/dunyaya-rezil-olduk-faruk-kocanin-halil-umut-melere-saldirisi-dis-basinda-hakeme-vahsi-saldiri-42374560" target="_blank" title="Dünyaya rezil olduk! Halil Umut Melere saldırı dış basında">Dünyaya rezil olduk! Halil Umut Meler'e saldırı dış basında</a>,
    <a class="current-news__title" href="/sporarena/halil-umut-melere-meslektaslarindan-destek-firat-aydinus-bu-fotograflara-iyi-bakin-kararinizi-alin-42374661" target="_blank" title="Halil Umut Melere meslektaşlarından destek">Halil Umut Meler'e meslektaşlarından destek</a>,
    <a class="current-news__title" href="/sporarena/son-dakika-hakem-halil-umut-melere-yumruklu-saldiri-42374519" target="_blank" title="Türk futbolunun utanç gecesi! Yerde de defalarca tekmelediler...">Türk futbolunun utanç gecesi! Yerde de defalarca tekmelediler...</a>,
    <a class="current-news__title" href="/sporarena/son-dakika-spor-yorumcularindan-sert-tepki-hakemler-maclara-cikmaz-42374527" target="_blank" title="Bakan Yerlikaya: İki kişi gözaltında"> Bakan Yerlikaya: İki kişi gözaltında</a>
'''
]


for item in html_list:
    soup = BeautifulSoup(item, 'html.parser')

    # div elementi içindeki a etiketini bul
    a_element = soup.find('a')

    # a elementinin metin içeriğini al
    content = a_element.text.strip()

    # a elementinin href özelliğini al (link)
    link = a_element['href']

    print(f"Content: {content}, Link: {link}")

with open("hurriyet.txt", "w", encoding="utf-8") as dosya:
    for baslik in title:
        dosya.write(baslik.text.strip() + "\n")

with open("hurriyet.txt", "a", encoding="utf-8") as dosya:
    for baslik in title4:
        dosya.write(baslik.text.strip() + "\n")