# -*- coding: utf-8 -*-
"""resmi_gazete.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wBAl9iWCCSxo7WEa_9EwX0tugiE84Y-H
"""

!pip install beautifulSoup

!pip install requests

import pandas as pd
import requests
from bs4 import BeautifulSoup

url = "https://www.resmigazete.gov.tr/11.12.2023"

response = requests.get(url)

soup = BeautifulSoup(response.content, "html.parser")

soup

title = soup.find_all("div", attrs={'class':'card-title html-title' })

title[0].text.strip()

title[1].text.strip()

with open("sonuclar.txt", "w", encoding="utf-8") as dosya:
    for baslik in title:
        dosya.write(baslik.text.strip() + "\n")

sub_title = soup.find("div", attrs={'class':'html-subtitle' })

# div elementinin içeriğini al
content = sub_title.text.strip()

content

links = soup.find_all("div", attrs={'class':'fihrist-item mb-1' })

links

html_list = [ '''
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-1.htm">–– Dokuz Eylül Üniversitesi Ege Bölgesi Uygulama ve Araştırma Merkezi Yönetmeliği</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-2.htm">–– Dokuz Eylül Üniversitesi Fauna ve Flora Araştırma ve Uygulama Merkezi Yönetmeliği</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-3.htm">–– Dokuz Eylül Üniversitesi İzmir İli Stratejik Planlama, Yönetişim, Araştırma ve Uygulama Merkezi Yönetmeliği</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-4.htm">–– Dokuz Eylül Üniversitesi Mevlâna Uygulama ve Araştırma Merkezi (DEÜMAM) Yönetmeliği</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-5.htm">–– Dokuz Eylül Üniversitesi Stratejik Araştırmalar Uygulama ve Araştırma Merkezi Yönetmeliği</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-6.htm">–– İstanbul Atlas Üniversitesi Ön Lisans ve Lisans Eğitim-Öğretim ve Sınav Yönetmeliğinde Değişiklik Yapılmasına Dair Yönetmelik</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-7.htm">–– Kadir Has Üniversitesi Lisans Eğitim ve Öğretim Yönetmeliğinde Değişiklik Yapılmasına Dair Yönetmelik</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2023/12/20231211-2.htm">a - Yargı İlânları</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2023/12/20231211-3.htm">b - Artırma, Eksiltme ve İhale İlânları</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2023/12/20231211-4.htm">c - Çeşitli İlânlar</a></div>,
    <div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2023/12/20231211-5.htm">– T.C. Merkez Bankasınca Belirlenen Devlet İç Borçlanma Senetlerinin Günlük Değerleri</a></div>
    '''
    ]

for item in html_list:
    soup = BeautifulSoup(item, 'html.parser')

    # div elementi içindeki a etiketini bul
    a_element = soup.find('a')

    # a elementinin metin içeriğini al
    content = a_element.text.strip()

    print(content)

html_list = [
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-1.htm">–– Dokuz Eylül Üniversitesi Ege Bölgesi Uygulama ve Araştırma Merkezi Yönetmeliği</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-2.htm">–– Dokuz Eylül Üniversitesi Fauna ve Flora Araştırma ve Uygulama Merkezi Yönetmeliği</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-3.htm">–– Dokuz Eylül Üniversitesi İzmir İli Stratejik Planlama, Yönetişim, Araştırma ve Uygulama Merkezi Yönetmeliği</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-4.htm">–– Dokuz Eylül Üniversitesi Mevlâna Uygulama ve Araştırma Merkezi (DEÜMAM) Yönetmeliği</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-5.htm">–– Dokuz Eylül Üniversitesi Stratejik Araştırmalar Uygulama ve Araştırma Merkezi Yönetmeliği</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-6.htm">–– İstanbul Atlas Üniversitesi Ön Lisans ve Lisans Eğitim-Öğretim ve Sınav Yönetmeliğinde Değişiklik Yapılmasına Dair Yönetmelik</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/eskiler/2023/12/20231211-7.htm">–– Kadir Has Üniversitesi Lisans Eğitim ve Öğretim Yönetmeliğinde Değişiklik Yapılmasına Dair Yönetmelik</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2023/12/20231211-2.htm">a - Yargı İlânları</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2023/12/20231211-3.htm">b - Artırma, Eksiltme ve İhale İlânları</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2023/12/20231211-4.htm">c - Çeşitli İlânlar</a></div>',
    '<div class="fihrist-item mb-1"><a data-modal="True" href="https://www.resmigazete.gov.tr/ilanlar/eskiilanlar/2023/12/20231211-5.htm">– T.C. Merkez Bankasınca Belirlenen Devlet İç Borçlanma Senetlerinin Günlük Değerleri</a></div>'
    ]

for item in html_list:
    soup = BeautifulSoup(item, 'html.parser')

    # div elementi içindeki a etiketini bul
    a_element = soup.find('a')

    # a elementinin metin içeriğini al
    content = a_element.text.strip()

    # a elementinin href özelliğini al (link)
    link = a_element['href']

    print(f"Content: {content}, Link: {link}")

link = soup.find_all("a", attrs={'data-modal':'True' })

link[0].get('href')

header = soup.find_all("div", attrs={'class':'d-block m-0 p-0' })

sub_header = soup.find_all("span")

li = soup.find_all("li", attrs={'class': 'list-group-item p-1'})

html_list = [
    '<li class="list-group-item p-1"><a href="#" id="tarihce">Resmî Gazete Tarihçesi</a></li>',
    '<li class="list-group-item p-1"><a href="#" id="mevzuat">Resmî Gazete Mevzuatı</a></li>',
    '<li class="list-group-item p-1"><a href="https://www.mevzuat.gov.tr/" target="_blank">Mevzuat Bilgi Sistemi</a></li>',
]

for item in html_list:
    soup = BeautifulSoup(item, 'html.parser')

    # li elementi içindeki a etiketini bul
    a_element = soup.find('a')

    # a elementinin metin içeriğini al
    content = a_element.text.strip()

    # a elementinin href özelliğini al (link)
    link = a_element.get('href')

    print(f"Content: {content}, Link: {link}")

ul = soup.find_all("ul", attrs={'class': 'list-inline mb-0 mt-3 mt-xl-0'})

html_content = '''
<ul class="list-inline mb-0 mt-3 mt-xl-0">
 <li class="list-inline-item mr-0"><a href="tel:+903125253427"><i class="fas fa-phone"></i> 0 (312) 525 3427</a></li>
 <li class="list-inline-item mr-0">-</li>
 <li class="list-inline-item"><a href="tel:+903125253395">0 (312) 525 3395</a></li>
 <li class="list-inline-item"><a data-target="#ContactFormModal" data-toggle="modal" href="#"><i class="fas fa-envelope ml-2"></i> Bize Ulaşın</a></li>
 <li class="list-inline-item"><a href="https://atlas.harita.gov.tr/#13/39.93089/32.7990" target="_blank"><i class="fas fa-map-marker-alt ml-2"></i> Haritada göster</a></li>
</ul>
'''

soup = BeautifulSoup(html_content, 'html.parser')

list_items = soup.find_all('li', class_='list-inline-item')

for item in list_items:
    # a etiketini bul
    a_element = item.find('a')

    # a etiketi var mı kontrol et
    if a_element:
        # metin içeriğini al
        content = a_element.text.strip()

        # href özelliğini al (link)
        link = a_element.get('href')

        print(f"Content: {content}, Link: {link}")
    else:
        # a etiketi yoksa li etiketini kullan
        content = item.text.strip()
        print(f"Content: {content}")

"""*****************************************************************************************************************************************************************************************************************************************"""